// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLYQwwaeWi71UlN3CT6PZ_G4yTGBFciDI',
    appId: '1:176641543662:web:f5df757a125290fb7b12ff',
    messagingSenderId: '176641543662',
    projectId: 'famscreen-4356c',
    authDomain: 'famscreen-4356c.firebaseapp.com',
    storageBucket: 'famscreen-4356c.appspot.com',
    measurementId: 'G-EKVBBSK7C0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPFARvU3puxH46KZnMTS8oz8w3UTTx_Sc',
    appId: '1:176641543662:android:0a799dab6481a6f07b12ff',
    messagingSenderId: '176641543662',
    projectId: 'famscreen-4356c',
    storageBucket: 'famscreen-4356c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDydw_R4Nj8Wwqx54xVtQFdfqHQ9gstZMI',
    appId: '1:176641543662:ios:12b52ea771575bbc7b12ff',
    messagingSenderId: '176641543662',
    projectId: 'famscreen-4356c',
    storageBucket: 'famscreen-4356c.appspot.com',
    iosBundleId: 'com.example.projek',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDydw_R4Nj8Wwqx54xVtQFdfqHQ9gstZMI',
    appId: '1:176641543662:ios:12b52ea771575bbc7b12ff',
    messagingSenderId: '176641543662',
    projectId: 'famscreen-4356c',
    storageBucket: 'famscreen-4356c.appspot.com',
    iosBundleId: 'com.example.projek',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLYQwwaeWi71UlN3CT6PZ_G4yTGBFciDI',
    appId: '1:176641543662:web:949a9bb9e686b3677b12ff',
    messagingSenderId: '176641543662',
    projectId: 'famscreen-4356c',
    authDomain: 'famscreen-4356c.firebaseapp.com',
    storageBucket: 'famscreen-4356c.appspot.com',
    measurementId: 'G-75XTD3TQEP',
  );
}
